### ISSUE TITLE
import error in "great-big-example-application/src/main/webapp/app/layouts/layout-routing.module.ts

### ISSUE THREAD

**Issue by shinjigi** [dancancro/great-big-example-application#31]
Hi Dan,
Is "errorRoute"  a const imported from error folder?

**Comment by dancancro** [comment]
Yes. It is defined [here](https://github.com/dancancro/great-big-example-application/blob/master/src/main/webapp/app/layouts/error/error.route.ts#L6).

**Comment by shinjigi** [comment]
how import works?

Why the compiler does not return error on:
`import { errorRoute } from './';`

It should not be?
`import { errorRoute } from './error/error.route';`

**Comment by dancancro** [comment]
That would work too.

It works as it is because of [this file](https://github.com/dancancro/great-big-example-application/blob/master/src/main/webapp/app/layouts/index.ts) which refers to `error.route.ts`.

`index.ts` files are special. They are sometimes called barrels. You can refer to a directory, like `./` without including the file name like `./index`. The system will look for a file in that directory by the name `index.ts` and it will still work.

I don't really like `index.ts` files because it makes things less clear and it creates an unnecessary level of indirection in my opinion. When adding demos to the project I often get rid of them. If someone would like to explain how they make things better I'd be happy to learn.

This one is there because it was generated by jhipster, and so far, I have left most of the jhipster stuff alone.

**Comment by shinjigi** [comment]
Thanks a lot for the explanation... I'm really inexperienced.
